/* ============================================================================
   French dictionary — batch 7: the "Apply <board> defaults" button labels and
   the per-board PINMAP notes. These are written to data-no-i18n elements via
   JS (refreshBoardDefaultsButton), which looks them up here through tr().
   Merged into window.I18N_FR; loaded before i18n.js.
   ========================================================================== */
window.I18N_FR = Object.assign(window.I18N_FR || {}, {
  /* ---- button labels (Apply <label> defaults) ---- */
  "Apply FYSETC E4 defaults": "Appliquer les valeurs par défaut FYSETC E4",
  "Apply MaxESP3 defaults": "Appliquer les valeurs par défaut MaxESP3",
  "Apply MaxESP4 defaults": "Appliquer les valeurs par défaut MaxESP4",
  "Apply MaxPCB4 defaults": "Appliquer les valeurs par défaut MaxPCB4",
  "Apply MaxSTM3 defaults": "Appliquer les valeurs par défaut MaxSTM3",
  "Apply MaxSTM3I defaults": "Appliquer les valeurs par défaut MaxSTM3I",
  "Apply FYSETC S6 V1.2 defaults": "Appliquer les valeurs par défaut FYSETC S6 V1.2",
  "Apply FYSETC S6 V2.0 defaults": "Appliquer les valeurs par défaut FYSETC S6 V2.0",
  "Apply BTT SKR PRO V1.2 defaults": "Appliquer les valeurs par défaut BTT SKR PRO V1.2",
  "Apply MiniPCB v1 defaults": "Appliquer les valeurs par défaut MiniPCB v1",
  "Apply MiniPCB v2 defaults": "Appliquer les valeurs par défaut MiniPCB v2",
  "Apply CNC3 / WeMos D1 R32 (ESP32) defaults": "Appliquer les valeurs par défaut CNC3 / WeMos D1 R32 (ESP32)",
  "Pick a PINMAP first.": "Choisissez d'abord un PINMAP.",

  /* ---- per-board notes ---- */
  "Click: fetches the Config.h from hjd1964/OnStepX branch \"E4\" (180+ fields) into the Output tab, keeps Source ref on main (latest OnStepX), and ticks the Website plugin. Matches Howard's documented E4 + Website build.": "Au clic : récupère le Config.h de la branche « E4 » de hjd1964/OnStepX (180+ champs) dans l'onglet Sortie, garde la réf. source sur main (dernier OnStepX), et coche le plugin Website. Correspond à la build E4 + Website documentée par Howard.",
  "ESP32-based predecessor to MaxESP4. Default driver mix is TMC2209 UART on the mount axes and focuser; if your MaxESP3 was wired for SPI drivers (TMC2130 etc.) override the driver-model fields below. Note: this pinmap routes both STATUS_LED and STATUS_BUZZER to the same AUX8_PIN, so we default the buzzer OFF — flip it back ON only if you set STATUS_LED=OFF.": "Prédécesseur du MaxESP4, basé sur ESP32. Le mélange de drivers par défaut est TMC2209 UART sur les axes de la monture et le focuser ; si votre MaxESP3 était câblé pour des drivers SPI (TMC2130, etc.), modifiez les champs de modèle de driver ci-dessous. Note : ce pinmap route STATUS_LED et STATUS_BUZZER vers la même AUX8_PIN, nous mettons donc le buzzer sur OFF par défaut — ne le remettez sur ON que si vous réglez STATUS_LED=OFF.",
  "ESP32 with 4× TMC2209 UART drivers on a shared serial bus. All axes use TMC2209. Note: STATUS_LED and STATUS_BUZZER both default to GPIO 12 on this pinmap, so we default the buzzer OFF — flip it back ON only if you set STATUS_LED=OFF.": "ESP32 avec 4× drivers TMC2209 UART sur un bus série partagé. Tous les axes utilisent le TMC2209. Note : STATUS_LED et STATUS_BUZZER pointent tous deux par défaut vers GPIO 12 sur ce pinmap, nous mettons donc le buzzer sur OFF par défaut — ne le remettez sur ON que si vous réglez STATUS_LED=OFF.",
  "Teensy 4.1. Pinmap is wired for 4× TMC2209 UART step drivers (Serial8, 460800 baud). All axes use TMC2209.": "Teensy 4.1. Le pinmap est câblé pour 4× drivers de pas TMC2209 UART (Serial8, 460800 baud). Tous les axes utilisent le TMC2209.",
  "STM32F411. Pinmap is wired for TMC SPI drivers (shared MOSI/SCK/MISO bus). All axes use TMC2130 (TMC5160 also works — swap the #define).": "STM32F411. Le pinmap est câblé pour des drivers TMC SPI (bus MOSI/SCK/MISO partagé). Tous les axes utilisent le TMC2130 (le TMC5160 fonctionne aussi — changez le #define).",
  "MaxSTM3 with integrated STM32F411CE + onboard M24C64 EEPROM (8KB). Same TMC SPI driver bus as MaxSTM3 — defaults to TMC2130.": "MaxSTM3 avec STM32F411CE intégré + EEPROM M24C64 embarquée (8 Ko). Même bus de drivers TMC SPI que le MaxSTM3 — TMC2130 par défaut.",
  "STM32F446VE, 6-axis 3D-printer board. ⚠ Per the OnStep wiki: only TMC2130 / TMC5160 (SPI), LV8729 or S109 are supported here — TMC2208 / TMC2209 / TMC2226 UART steppers will NOT work on this board. Defaults assume TMC2130 SPI on all stepper sticks. Flash via WebUSB DFU (BOOT0 jumper + reset).": "STM32F446VE, carte d'imprimante 3D 6 axes. ⚠ Selon le wiki OnStep : seuls les TMC2130 / TMC5160 (SPI), LV8729 ou S109 sont pris en charge ici — les moteurs UART TMC2208 / TMC2209 / TMC2226 ne fonctionneront PAS sur cette carte. Les valeurs par défaut supposent du TMC2130 SPI sur tous les sticks. Flash via WebUSB DFU (cavalier BOOT0 + reset).",
  "STM32F446VE, 6-axis 3D-printer board, V2.0 connector layout. ⚠ Per the OnStep wiki: only TMC2130 / TMC5160 (SPI), LV8729 or S109 are supported here — TMC2208 / TMC2209 / TMC2226 UART steppers will NOT work on this board. Defaults assume TMC2130 SPI. Flash via WebUSB DFU (BOOT0 jumper + reset).": "STM32F446VE, carte d'imprimante 3D 6 axes, brochage des connecteurs V2.0. ⚠ Selon le wiki OnStep : seuls les TMC2130 / TMC5160 (SPI), LV8729 ou S109 sont pris en charge ici — les moteurs UART TMC2208 / TMC2209 / TMC2226 ne fonctionneront PAS sur cette carte. Les valeurs par défaut supposent du TMC2130 SPI. Flash via WebUSB DFU (cavalier BOOT0 + reset).",
  "BigTreeTech 3D-printer board repurposed for OnStep (STM32F407ZGT6). Defaults assume TMC2209 UART step-sticks — if you've got TMC5160 SPI drivers plugged in, override the driver-model fields. Flash via WebUSB DFU (BOOT0 jumper + reset to enter DFU mode).": "Carte d'imprimante 3D BigTreeTech réutilisée pour OnStep (STM32F407ZGT6). Les valeurs par défaut supposent des sticks TMC2209 UART — si vous avez des drivers TMC5160 SPI branchés, modifiez les champs de modèle de driver. Flash via WebUSB DFU (cavalier BOOT0 + reset pour entrer en mode DFU).",
  "Compact 2-axis OnStep design intended to embed inside the mount body. Runs on Teensy 3.2 (moderately fast) or Teensy 4.0 (very fast — pick teensy40 on the Compile tab). Works with most StepStick drivers (DRV8825 / A4988 / LV8729), plus TMC2130 and TMC5160. Defaults below assume DRV8825 step-sticks; override AXIS_DRIVER_MODEL if you have TMC SPI drivers wired in. Note: Teensy 4.0 has only ~1KB EEPROM emulation vs Teensy 3.2's 2KB — affects catalog/PEC storage size.": "Conception OnStep compacte 2 axes destinée à être intégrée dans le corps de la monture. Tourne sur Teensy 3.2 (modérément rapide) ou Teensy 4.0 (très rapide — choisissez teensy40 dans l'onglet Compiler). Compatible avec la plupart des drivers StepStick (DRV8825 / A4988 / LV8729), plus TMC2130 et TMC5160. Les valeurs par défaut ci-dessous supposent des sticks DRV8825 ; modifiez AXIS_DRIVER_MODEL si vous avez des drivers TMC SPI câblés. Note : le Teensy 4.0 n'a que ~1 Ko d'émulation EEPROM contre 2 Ko pour le Teensy 3.2 — cela affecte la taille de stockage du catalogue/PEC.",
  "Stand-alone 2-axis OnStep controller designed for a small aluminium project box. Runs on Teensy 3.2 (moderately fast) or Teensy 4.0 (very fast — pick teensy40 on the Compile tab). Works with most StepStick drivers (DRV8825 / A4988 / LV8729), plus TMC2130 and TMC5160. Defaults below assume DRV8825 step-sticks; override AXIS_DRIVER_MODEL for TMC. Onboard WeMos D1 Mini header for WiFi.": "Contrôleur OnStep autonome 2 axes conçu pour un petit boîtier aluminium. Tourne sur Teensy 3.2 (modérément rapide) ou Teensy 4.0 (très rapide — choisissez teensy40 dans l'onglet Compiler). Compatible avec la plupart des drivers StepStick (DRV8825 / A4988 / LV8729), plus TMC2130 et TMC5160. Les valeurs par défaut ci-dessous supposent des sticks DRV8825 ; modifiez AXIS_DRIVER_MODEL pour le TMC. En-tête WeMos D1 Mini embarqué pour le WiFi.",
  "Arduino CNC Shield V3 on WeMos D1 R32 (ESP32). Deprecated per the OnStep wiki — kept for legacy builds. Recommended drivers per the wiki: LV8729 or S109 at 12V. Default below uses LV8729.": "Arduino CNC Shield V3 sur WeMos D1 R32 (ESP32). Déprécié selon le wiki OnStep — conservé pour les anciennes builds. Drivers recommandés selon le wiki : LV8729 ou S109 en 12V. La valeur par défaut ci-dessous utilise le LV8729."
});
